# Generated by Django 2.2.10 on 2020-03-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinalBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestId', models.IntegerField()),
                ('totalAmount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=50)),
                ('itemPrice', models.IntegerField()),
                ('itemqty', models.IntegerField()),
                ('itemqtyAdd', models.IntegerField()),
                ('itemType', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('requestId', models.AutoField(primary_key=True, serialize=False)),
                ('totalAmount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shopId', models.AutoField(primary_key=True, serialize=False)),
                ('shopName', models.CharField(max_length=50)),
                ('shopZone', models.IntegerField()),
                ('shopContact', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50)),
                ('userAddress', models.CharField(max_length=100)),
                ('userContact', models.CharField(max_length=10)),
            ],
        ),
    ]
